{% set data= load_setup_py_data() %}
package:
  name: ts-audiotrigger
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.4

  source_files:
    - python
    - tests
    - setup.py
    - pyproject.toml
  commands:
    - run_audiotrigger -h
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - wheel
    - setuptools_scm
    - setuptools
      
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.4
  run:
    - python {{ python }}
    - numpy =1.25
    - scipy =1.11
    - pigpio =1.78
    - python-sounddevice =0.5
    - ts-tcpip =2.0
    - pyserial =3.5
    - ts-utils =1.2
